### ISSUE TITLE
Add plus for new header from popup menu

### ISSUE THREAD

**Issue by sshaplygin** [sshaplygin/modheader#8]

**Comment by woeterman94** [comment]
The add button doesn't work. Any idea on how to fix it?

**Comment by sshaplygin** [comment]
> The add button doesn't work

Hey, @woeterman94 Thanks for feedback :) it is working but you need change default profiles name. When we are started extension. The function witch work for duplicated profiles doesn't work and throw exception )) 

LOL, i found bug :) in code tried increments const vars looks [this line](https://github.com/sshaplygin/modheader/blob/master/src/scripts/main.js#L140)

i fixed this incorrect behaviour https://github.com/sshaplygin/modheader/pull/13 but i couldn't fix save profiles on local storage at new open extension popup session :(

**Comment by sshaplygin** [comment]
any updates in next issue https://github.com/sshaplygin/modheader/issues/14
